site_name: MoreThanAChatBot
site_description: Resources for LLMs
site_author: Team MoreThanAChatBot

repo_url: https://github.com/ahuang11/MoreThanAChatBot
repo_name: ahuang11/MoreThanAChatBot
edit_uri: edit/main/docs/

theme:
    name: material
    logo: 'assets/logo.png'
    features:
        - announce.dismiss
        - content.action.edit
        - content.action.view
        - content.code.annotate
        - content.code.copy
        - content.tooltips
        - navigation.footer
        - navigation.indexes
        - navigation.sections
        - navigation.top
        - search.highlight
        - search.suggest
        - toc.follow
    palette:
        # Palette toggle for light mode
        - media: "(prefers-color-scheme: light)"
          scheme: default
          primary: white
          accent: blue
          toggle:
            icon: material/brightness-7
            name: Switch to dark mode

        # Palette toggle for dark mode
        - media: "(prefers-color-scheme: dark)"
          scheme: slate
          primary: black
          accent: blue
          toggle:
            icon: material/brightness-4
            name: Switch to light mode

markdown_extensions:
    - toc:
        baselevel: 1
        permalink: true
    - pymdownx.highlight:
        anchor_linenums: true
    - pymdownx.tasklist:
        custom_checkbox: true
    - pymdownx.inlinehilite
    - pymdownx.snippets
    - pymdownx.superfences
    - admonition

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          options:
            docstring_style: google
            show_if_no_docstring: true
            merge_init_into_class: true
            filters:
            - "!^_"

watch:
    - docs

nav:
    - Home: index.md
    - Level 1: 
        - Overview: level1/overview
        - Providers: level1/providers
        - Models: level1/models
        - Gateways: level1/gateways
        - Tips & Tricks: level1/tips_and_tricks
        - Case Studies:
            - Prompting with ChatGPT: level1/chatgpt
            - Getting Started with Gemini: level1/gemini
            - Pitfalls of Gemini: level1/Pitfall_of_Gemini
            - Intro to Deepseek: level1/deepseek
            - Using Claude: level1/Using_Claude_to_interpret_plots
            - Search using Perplexity: level1/Perplexity_for_research
            - Geospatial EML Tutorial: level1/geospat_eml_tutorial_chatgpt
    - Level 2:
        - Overview: level2/overview
        - Cursor: level2/cursor
    - Level 3:
        - Overview: level3/overview
        - LLM in R: level3/R_example
        - Deploying LLM Workflows: level3/marvin_ai
        - Sentiment Analysis: level3/Sentiment_Analysis
